base:
  - ../../parts/curved_base/internal.convex/cut_stone_curved_base.
  - .internal.convex.stl
back:
  - ../../parts/curved_back/internal.standard/cut_stone_curved_back.
  - .internal.standard.stl
min: 1
max: 4
result:
  - cut_stone_curved.
  - .internal.convex.stl
