base:
  - ../../parts/curved_base/internal.concave/cut_stone_curved_base.
  - .internal.concave.stl
back:
  - ../../parts/curved_back/internal.standard/cut_stone_curved_back.
  - .internal.standard.stl
min: 1
max: 4
result:
  - cut_stone_curved.
  - .internal.concave.stl
