base:
  - ../../parts/corner_base/internal/cut_stone_corner_base.
  - .internal.stl
back:
  - ../../parts/corner_back/internal.half/cut_stone_corner_back.
  - .internal.half.stl
min: 1
max: 4
result:
  - cut_stone_corner.
  - .internal.half.stl
