base:
  - ../../parts/wall_base/internal/cut_stone_wall_base.
  - .internal.stl
back:
  - ../../parts/window/window_back.
  - .internal.standard.stl
x-min: 2 
x-max: 4
y-min: 1
y-max: 4
result:
  - cut_stone_window.
  - .internal.standard.stl
external: false
