base:
  - ../../parts/wall_base/internal/cut_stone_wall_base.
  - .internal.stl
back:
  - ../../parts/arrow_slit/arrow_slit_wall.internal.standard/cut_stone_arrow_slit.
  - .internal.standard.1.stl
x-min: 1
x-max: 4
y-min: 1
y-max: 4
result:
  - cut_stone_arrow_slit_wall.
  - .internal.standard.stl
external: false
