base:
  - ../../parts/corridor_base/internal/cut_stone_corridor_base.
  - .internal.stl
back:
  - ../../parts/wall_back/internal.standard/cut_stone_wall_back.
  - .internal.standard.1.stl
front:
  - ../../parts/wall_back/internal.standard/cut_stone_wall_back.
  - .internal.standard.2.stl
x-min: 1
x-max: 4
y-min: 2
y-max: 4
result:
  - cut_stone_corridor.
  - .internal.stl
external: false
